name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login
      uses: docker/login-action@v3.4.0
      with: 
        username: ${{secrets.DOCKER_HUB_USER}}
        password: ${{secrets.DOCKER_HUB_TOKEN}}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.15.0
